apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-example-frontend
  labels:
      app.plaidcloud.com/app: plaidcloud
      app.plaidcloud.com/component: example-frontend
      release: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.plaidcloud.com/app: plaidcloud
      app.plaidcloud.com/component: example-frontend
  template:
    metadata:
      labels:
        app.plaidcloud.com/app: plaidcloud
        app.plaidcloud.com/component: example-frontend
        release: {{ .Release.Name }}
    spec:
      volumes:
      - name: example-volume
        configMap:
          name: example-configmap
      containers:
      - name: example-frontend
        image: nginxdemos/hello:0.4
        {{/*
          If using your own protected image repository, uncomment the imagePullSecret key in the line below
          and include the name of the pull secret. We provide a pullsecret-example.yaml file for reference.
        */}}
        # imagePullSecret: example-key
        {{/*
          If you have known resource requirements for application functionality, you may set them here.
        */}}
          requests:
            cpu: 50m
            memory: 250Mi
        {{/*
          Below is an example of how to mount a config file at a specific path in a pod. This is a common
          technique to maintain configs outside of deployed pods.
        */}}
        volumeMounts:
          - name: example-volume
            mountPath: {{ .Values.exampleValues.mountPath }}
            readonly: true
        env:
          - name: EXAMPLE_ENV_VAR_FROM_CONFIGMAP
            valueFrom:
              configMapKeyRef:
                name: example-configmap
                key: example_key
        # Any ports that need opened for the running application should be defined here.    
        ports:
          - name: http
            containerPort: 80
